Ising cluster update code
ev-br/mc_lib pull request #22
Opened 2021-07-04 11:25 UTC by MoskalenkoRomanBorisovich

2021-07-04 18:24 UTC, ev-br requested changes
Несколько комментариев. Прдправляйте и в ту же ветку коммит.

2021-07-04 18:24 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +
Четыре это двумерие, макс координат число равно четырем? Лучше его сосчитать по массиву neighbors.

2021-07-04 18:24 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +                    break
O(размер кластера). М.б. тут использовать std::set?

2021-07-04 18:24 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +                         RndmWrapper rndm):
Тут пжлст docstring, в нём сказать что это алг Вольфа + ссылку на например, Вернера краута, где он описан

2021-07-26 12:11 UTC, ev-br commented
Tried to run a simulation of a 4x4 lattice, and I cannot make sense of the results:

```
In [15]: neighb = tabulate_neighbors((4, 4, 1), 'sc')

In [16]: simulate(4, neighb, 1.0, num_sweeps=200, verbose=2)
beta =  1.0   T =  1.0
Conformation size = 4

----- sweep =  0 spins =  [1 1 1 1] beta =  1.0
  ene =  -17506370211986.125  (naive)
      =  -17506370211986.125 +/- 0.0
  mag^2 =  1.0 +/- 0.0
  mag^4 =  1.0 +/- 0.0

Final:
  ene =  -525191071711.79  (naive)
  ene =  -547074033033.0678 +/- 1237330116550.454
  mag^2 =  0.9505208333333334 +/- 0.015259024159068463
  mag^4 =  0.9446614583333334 +/- 0.01665360680811597
```

- What is the conformation size, and why there are four spins --- does this simulate 16 spins on a 4x4 lattice with PBC, or 4 spins on a 4x4 lattice or something else?

- Energy is dubious

Could you please explain / update the PR @MoskalenkoRomanBorisovich ?

2021-07-26 12:15 UTC, ev-br commented
W.r.t. reading the structure, what you have here is nice but what's really needed is an example of building a lattice out of it. Maybe a simpler, shorter conformation where you can follow the site numbering and neighbors. THis is best left for a separate PR though.

2021-07-31 17:10 UTC, MoskalenkoRomanBorisovich commented
> Tried to run a simulation of a 4x4 lattice, and I cannot make sense of the results:
> 
> ```
> In [15]: neighb = tabulate_neighbors((4, 4, 1), 'sc')
> 
> In [16]: simulate(4, neighb, 1.0, num_sweeps=200, verbose=2)
> beta =  1.0   T =  1.0
> Conformation size = 4
> 
> ----- sweep =  0 spins =  [1 1 1 1] beta =  1.0
>   ene =  -17506370211986.125  (naive)
>       =  -17506370211986.125 +/- 0.0
>   mag^2 =  1.0 +/- 0.0
>   mag^4 =  1.0 +/- 0.0
> 
> Final:
>   ene =  -525191071711.79  (naive)
>   ene =  -547074033033.0678 +/- 1237330116550.454
>   mag^2 =  0.9505208333333334 +/- 0.015259024159068463
>   mag^4 =  0.9446614583333334 +/- 0.01665360680811597
> ```
> 
> * What is the conformation size, and why there are four spins --- does this simulate 16 spins on a 4x4 lattice with PBC, or 4 spins on a 4x4 lattice or something else?
> * Energy is dubious
> 
> Could you please explain / update the PR @MoskalenkoRomanBorisovich ?

L is the number of spins, for a 4 * 4 grid this is 16, not 4. This is a rudiment left from cy_ising.pyx, I will remove it in the next commit

2021-08-05 12:00 UTC, ev-br commented
Please add a usage example. Ideally, add a comparison to exact enumeration for a 4x4 lattice. Enumeration might live in a Jupyter notebook or a python script or a cython code, whichever is simpler for you.

2021-11-15 15:46 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +    num_therm - number of thermolisation sweeps
```suggestion
    num_therm - number of thermalization sweeps
```

2021-11-15 15:47 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +    do_intermediate_measure - 1 means function will return an array of enery values measured during the calculation (useful for determining convergence rate)
please wrap too-long lines

2021-11-15 15:47 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +    upd_per_sweep - number of claster updates per sweep
```suggestion
    upd_per_sweep - number of cluster updates per sweep
```

2021-11-15 15:49 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +        int nDim = (neighbors.shape[1] - 1) // 2
Э, нет, это еще почему? в массиве `neighbors[0]` дает коорд число для каждого узла. То есть Вам нужно что-то вроде `nDim = max(neighbors[0, :])`

2021-11-15 15:49 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +    cdef double[::1] ratios = np.empty(nDim*4+1, dtype=float)
Почему `nDim*4 + 1`?

2021-11-15 15:50 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +    calc_ratios(ratios, beta, nDim)
назовите функцию `tabulate_ratios`

2021-11-15 15:50 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +    init_spins(spins, rndm)
`spins = init_spins(num_spins, rndm)`, c cоответствующими изменениями в `init_spins`

2021-11-15 15:52 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +             int num_therm = 100000,
pep8 говорит, что в этом случае нет пробелов вокруг знака равно: `num_therm=100000`

2021-11-15 15:53 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +             int verbose = 0,
`bint verbose`

2021-11-15 15:55 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +            ene_arr.append(copy.deepcopy(ene))
а зачем список объектов RealObservable?

2021-11-15 15:59 UTC, ev-br commented
Несколько комментариев по коду, исправляйте и push пжлст @MoskalenkoRomanBorisovich 

Дальше, точный пересчет произвольных решеток это зачетная попытка, но нужно убрать. Это плохой пример (экспоненциально малые значения в сумме; экспоненциально много членов в сумму). Нужно сделать проще пример, двумерную решетку 4-на-4, на питоне точный пересчет, прямо в ноутбуке. Как сделано для одномерия в https://github.com/ev-br/mc_lib/blob/master/examples/1DIsing.ipynb

Как сделаете, @-отметьте меня пожалуйста.

2021-11-15 16:03 UTC, ev-br commented on examples/Cluster_update_examples.ipynb
> +{
<p>typo strtUcture</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ev-br/mc_lib/pull/22/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2021-11-15 16:03 UTC, ev-br commented on examples/Cluster_update_examples.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    neighb = tabulate_neighbors((10, 10, 1), 'sc')
</pre><p>решетка 10х10 --- как это связано с предыдущим?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ev-br/mc_lib/pull/22/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2021-11-15 16:03 UTC, ev-br commented on examples/Cluster_update_examples.ipynb
> +{
<p>Прямо на питоне, для ясности. И предыдущий пример на той же решетке, 4х4 --- и тут и там.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ev-br/mc_lib/pull/22/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='10'/>

2021-11-15 16:03 UTC, ev-br commented on examples/Cluster_update_examples.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #6.    plt.errorbar(betas, ene_cluster, fmt='--o', label='cluster')
</pre><p><code>plt.errorbar(x, y, yerr=...)</code> to actually show the errorbars</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ev-br/mc_lib/pull/22/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2021-11-16 18:46 UTC, MoskalenkoRomanBorisovich commented on examples/cy_ising_cluster.pyx
> +            ene_arr.append(copy.deepcopy(ene))
Чтобы моно было следить за тем как алгоритм сходился во время выполнения

2021-11-17 16:12 UTC, MoskalenkoRomanBorisovich commented on examples/cy_ising_cluster.pyx
> +            ene_arr.append(copy.deepcopy(ene))
Когда я проверял сколько итераций нужно для нормальной сходимости решёток разных длин, я обычно запускал штук 10 разных решёток и потом строил графики по полученным массивам. По моему это удобнее чем читать 10 логов

2021-11-17 17:43 UTC, ev-br commented on examples/cy_ising_cluster.pyx
> +            ene_arr.append(copy.deepcopy(ene))
Ок, оставляйте. Пример имеет право быть слегка эзотерическим. Заодно демонстрирует необходимость deepcopy.
Комментарий пжлст добавьте

2021-11-18 19:53 UTC, MoskalenkoRomanBorisovich commented
@ev-br 
вроде всё поправил:
оставил решётку 4*4 с простым пересчётом на питоне
поправил опечатки
поменял поправил всё связанное с nDim в коде

2021-12-04 13:43 UTC, merged

2021-12-04 13:46 UTC, ev-br commented
Okay, let's merge it. Thanks @MoskalenkoRomanBorisovich 

Follow-ups in gh-53.